from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="Symptom",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("name",models.CharField(max_length=120)),("severity",models.PositiveSmallIntegerField()),("body_part",models.CharField(blank=True,max_length=120)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="symptoms",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Medication",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=150)),("dosage",models.CharField(blank=True,max_length=100)),("frequency",models.CharField(blank=True,max_length=100)),("start_date",models.DateField()),("end_date",models.DateField(blank=True,null=True)),("adherence",models.PositiveSmallIntegerField(default=0)),("active",models.BooleanField(default=True)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="medications",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Lifestyle",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("sleep_hours",models.DecimalField(blank=True,decimal_places=1,max_digits=4,null=True)),("mood",models.PositiveSmallIntegerField(blank=True,null=True)),("stress",models.PositiveSmallIntegerField(blank=True,null=True)),("nutrition",models.PositiveSmallIntegerField(blank=True,null=True)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="lifestyle",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="LabReport",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=200)),("report_date",models.DateField()),("file",models.FileField(upload_to="labs/")),("extracted_text",models.TextField(blank=True)),("analysis",models.JSONField(blank=True,default=dict)),("uploaded_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="labs",to=settings.AUTH_USER_MODEL))])
    ]
